---
- name: Configure Webserver with Nginx on Amazon Linux
  hosts: webservers
  become: true # This allows Ansible to use sudo on the remote machine
  tasks:
    - name: Install Nginx package (for RedHat/Amazon Linux)
      ansible.builtin.dnf:  # Changed from apt to dnf
        name: nginx
        state: present
        update_cache: yes # Similar to apt update_cache

    - name: Ensure Nginx service is running and enabled at boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple index.html file
      ansible.builtin.copy:
        content: "<h1>Hello from Ansible! Nginx is working on Amazon Linux!</h1>"
        dest: /usr/share/nginx/html/index.html # Default Nginx HTML directory for Amazon Linux
        mode: '0644'
